services:
  web:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/${IMAGE_NAME:-panpipe-team/backend-web-api}:latest
    build: 
      context: .
      target: final
    depends_on:
      - db
    ports:
      - ${WEB_API_PORT:-8080}:8080
  
  db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_USER=panpipe
      - POSTGRES_PASSWORD=panpipe
      - POSTGRES_DB=panpipe
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
