services:
  web:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/${IMAGE_NAME:-panpipe-team/backend-web-api}:latest
    build: 
      context: .
      target: final
    ports:
      - ${WEB_API_PORT:-8080}:8080
