services:
  web:
    image: ${CONTAINER_REGISTRY:-ghcr.io}/${IMAGE_NAME:-wrong-image-name-here}:latest
    build: 
      context: .
      target: final
    pull_policy: never
    ports:
      - ${WEB_API_PORT:-8080}:8080
